# coding: utf-8

"""
    FerryTix

    This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hendrik.lankers.hl@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_faehr_card_uuid_balance_get(self):
        """Test case for faehr_card_uuid_balance_get

        """
        pass

    def test_faehr_card_uuid_get(self):
        """Test case for faehr_card_uuid_get

        """
        pass

    def test_faehr_card_uuid_topup_post(self):
        """Test case for faehr_card_uuid_topup_post

        """
        pass

    def test_machines_default_config_patch(self):
        """Test case for machines_default_config_patch

        """
        pass

    def test_machines_get(self):
        """Test case for machines_get

        """
        pass

    def test_machines_uuid_commands_get(self):
        """Test case for machines_uuid_commands_get

        """
        pass

    def test_machines_uuid_commands_post(self):
        """Test case for machines_uuid_commands_post

        """
        pass

    def test_machines_uuid_config_patch(self):
        """Test case for machines_uuid_config_patch

        """
        pass

    def test_machines_uuid_get(self):
        """Test case for machines_uuid_get

        """
        pass

    def test_machines_uuid_replace_paper_roll_post(self):
        """Test case for machines_uuid_replace_paper_roll_post

        """
        pass

    def test_machines_uuid_status_get(self):
        """Test case for machines_uuid_status_get

        """
        pass

    def test_machines_uuid_status_patch(self):
        """Test case for machines_uuid_status_patch

        """
        pass

    def test_ticket_sales_post(self):
        """Test case for ticket_sales_post

        """
        pass

    def test_ticket_sales_uuid_invalidate_return_delete(self):
        """Test case for ticket_sales_uuid_invalidate_return_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
