# coding: utf-8

"""
    FerryTix

    This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hendrik.lankers.hl@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pay_pal_payment import PayPalPayment  # noqa: E501
from swagger_client.rest import ApiException


class TestPayPalPayment(unittest.TestCase):
    """PayPalPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayPalPayment(self):
        """Test PayPalPayment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pay_pal_payment.PayPalPayment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
