# coding: utf-8

"""
    FerryTix

    This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hendrik.lankers.hl@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CashPayment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'denominations': 'list[int]',
        'change': 'list[int]'
    }

    attribute_map = {
        'denominations': 'denominations',
        'change': 'change'
    }

    def __init__(self, denominations=None, change=None):  # noqa: E501
        """CashPayment - a model defined in Swagger"""  # noqa: E501
        self._denominations = None
        self._change = None
        self.discriminator = None
        if denominations is not None:
            self.denominations = denominations
        if change is not None:
            self.change = change

    @property
    def denominations(self):
        """Gets the denominations of this CashPayment.  # noqa: E501

        List of coins and bills the payment consists of.  # noqa: E501

        :return: The denominations of this CashPayment.  # noqa: E501
        :rtype: list[int]
        """
        return self._denominations

    @denominations.setter
    def denominations(self, denominations):
        """Sets the denominations of this CashPayment.

        List of coins and bills the payment consists of.  # noqa: E501

        :param denominations: The denominations of this CashPayment.  # noqa: E501
        :type: list[int]
        """

        self._denominations = denominations

    @property
    def change(self):
        """Gets the change of this CashPayment.  # noqa: E501

        List of coins and bills the change consists of.  # noqa: E501

        :return: The change of this CashPayment.  # noqa: E501
        :rtype: list[int]
        """
        return self._change

    @change.setter
    def change(self, change):
        """Sets the change of this CashPayment.

        List of coins and bills the change consists of.  # noqa: E501

        :param change: The change of this CashPayment.  # noqa: E501
        :type: list[int]
        """

        self._change = change

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CashPayment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CashPayment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
