# coding: utf-8

"""
    FerryTix

    This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hendrik.lankers.hl@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MachineStatusTicketsSoldToday(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'with_bicycle': 'int',
        'without_bicycle': 'int'
    }

    attribute_map = {
        'with_bicycle': 'withBicycle',
        'without_bicycle': 'withoutBicycle'
    }

    def __init__(self, with_bicycle=None, without_bicycle=None):  # noqa: E501
        """MachineStatusTicketsSoldToday - a model defined in Swagger"""  # noqa: E501
        self._with_bicycle = None
        self._without_bicycle = None
        self.discriminator = None
        if with_bicycle is not None:
            self.with_bicycle = with_bicycle
        if without_bicycle is not None:
            self.without_bicycle = without_bicycle

    @property
    def with_bicycle(self):
        """Gets the with_bicycle of this MachineStatusTicketsSoldToday.  # noqa: E501


        :return: The with_bicycle of this MachineStatusTicketsSoldToday.  # noqa: E501
        :rtype: int
        """
        return self._with_bicycle

    @with_bicycle.setter
    def with_bicycle(self, with_bicycle):
        """Sets the with_bicycle of this MachineStatusTicketsSoldToday.


        :param with_bicycle: The with_bicycle of this MachineStatusTicketsSoldToday.  # noqa: E501
        :type: int
        """

        self._with_bicycle = with_bicycle

    @property
    def without_bicycle(self):
        """Gets the without_bicycle of this MachineStatusTicketsSoldToday.  # noqa: E501


        :return: The without_bicycle of this MachineStatusTicketsSoldToday.  # noqa: E501
        :rtype: int
        """
        return self._without_bicycle

    @without_bicycle.setter
    def without_bicycle(self, without_bicycle):
        """Sets the without_bicycle of this MachineStatusTicketsSoldToday.


        :param without_bicycle: The without_bicycle of this MachineStatusTicketsSoldToday.  # noqa: E501
        :type: int
        """

        self._without_bicycle = without_bicycle

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MachineStatusTicketsSoldToday, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MachineStatusTicketsSoldToday):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
