# coding: utf-8

"""
    FerryTix

    This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hendrik.lankers.hl@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TopUp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        '_for': 'str',
        'issued_at': 'datetime',
        'issued_by': 'str',
        'amount': 'int',
        'paid': 'int',
        'payment': 'Payment',
        'initial': 'bool',
        'sale_counter': 'int',
        'signature': 'str'
    }

    attribute_map = {
        'uuid': 'uuid',
        '_for': 'for',
        'issued_at': 'issuedAt',
        'issued_by': 'issuedBy',
        'amount': 'amount',
        'paid': 'paid',
        'payment': 'payment',
        'initial': 'initial',
        'sale_counter': 'saleCounter',
        'signature': 'signature'
    }

    def __init__(self, uuid=None, _for=None, issued_at=None, issued_by=None, amount=None, paid=None, payment=None, initial=None, sale_counter=None, signature=None):  # noqa: E501
        """TopUp - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self.__for = None
        self._issued_at = None
        self._issued_by = None
        self._amount = None
        self._paid = None
        self._payment = None
        self._initial = None
        self._sale_counter = None
        self._signature = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if _for is not None:
            self._for = _for
        if issued_at is not None:
            self.issued_at = issued_at
        if issued_by is not None:
            self.issued_by = issued_by
        if amount is not None:
            self.amount = amount
        if paid is not None:
            self.paid = paid
        if payment is not None:
            self.payment = payment
        if initial is not None:
            self.initial = initial
        if sale_counter is not None:
            self.sale_counter = sale_counter
        if signature is not None:
            self.signature = signature

    @property
    def uuid(self):
        """Gets the uuid of this TopUp.  # noqa: E501


        :return: The uuid of this TopUp.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this TopUp.


        :param uuid: The uuid of this TopUp.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def _for(self):
        """Gets the _for of this TopUp.  # noqa: E501

        UUID of the FaehrCard the TopUp is for.  # noqa: E501

        :return: The _for of this TopUp.  # noqa: E501
        :rtype: str
        """
        return self.__for

    @_for.setter
    def _for(self, _for):
        """Sets the _for of this TopUp.

        UUID of the FaehrCard the TopUp is for.  # noqa: E501

        :param _for: The _for of this TopUp.  # noqa: E501
        :type: str
        """

        self.__for = _for

    @property
    def issued_at(self):
        """Gets the issued_at of this TopUp.  # noqa: E501


        :return: The issued_at of this TopUp.  # noqa: E501
        :rtype: datetime
        """
        return self._issued_at

    @issued_at.setter
    def issued_at(self, issued_at):
        """Sets the issued_at of this TopUp.


        :param issued_at: The issued_at of this TopUp.  # noqa: E501
        :type: datetime
        """

        self._issued_at = issued_at

    @property
    def issued_by(self):
        """Gets the issued_by of this TopUp.  # noqa: E501

        The id of the vending machine that the topup has been purchased at. Is null if purchased online  # noqa: E501

        :return: The issued_by of this TopUp.  # noqa: E501
        :rtype: str
        """
        return self._issued_by

    @issued_by.setter
    def issued_by(self, issued_by):
        """Sets the issued_by of this TopUp.

        The id of the vending machine that the topup has been purchased at. Is null if purchased online  # noqa: E501

        :param issued_by: The issued_by of this TopUp.  # noqa: E501
        :type: str
        """

        self._issued_by = issued_by

    @property
    def amount(self):
        """Gets the amount of this TopUp.  # noqa: E501


        :return: The amount of this TopUp.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this TopUp.


        :param amount: The amount of this TopUp.  # noqa: E501
        :type: int
        """

        self._amount = amount

    @property
    def paid(self):
        """Gets the paid of this TopUp.  # noqa: E501


        :return: The paid of this TopUp.  # noqa: E501
        :rtype: int
        """
        return self._paid

    @paid.setter
    def paid(self, paid):
        """Sets the paid of this TopUp.


        :param paid: The paid of this TopUp.  # noqa: E501
        :type: int
        """

        self._paid = paid

    @property
    def payment(self):
        """Gets the payment of this TopUp.  # noqa: E501


        :return: The payment of this TopUp.  # noqa: E501
        :rtype: Payment
        """
        return self._payment

    @payment.setter
    def payment(self, payment):
        """Sets the payment of this TopUp.


        :param payment: The payment of this TopUp.  # noqa: E501
        :type: Payment
        """

        self._payment = payment

    @property
    def initial(self):
        """Gets the initial of this TopUp.  # noqa: E501

        Describes whether the top up was done when the card was issued  # noqa: E501

        :return: The initial of this TopUp.  # noqa: E501
        :rtype: bool
        """
        return self._initial

    @initial.setter
    def initial(self, initial):
        """Sets the initial of this TopUp.

        Describes whether the top up was done when the card was issued  # noqa: E501

        :param initial: The initial of this TopUp.  # noqa: E501
        :type: bool
        """

        self._initial = initial

    @property
    def sale_counter(self):
        """Gets the sale_counter of this TopUp.  # noqa: E501


        :return: The sale_counter of this TopUp.  # noqa: E501
        :rtype: int
        """
        return self._sale_counter

    @sale_counter.setter
    def sale_counter(self, sale_counter):
        """Sets the sale_counter of this TopUp.


        :param sale_counter: The sale_counter of this TopUp.  # noqa: E501
        :type: int
        """

        self._sale_counter = sale_counter

    @property
    def signature(self):
        """Gets the signature of this TopUp.  # noqa: E501


        :return: The signature of this TopUp.  # noqa: E501
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature):
        """Sets the signature of this TopUp.


        :param signature: The signature of this TopUp.  # noqa: E501
        :type: str
        """

        self._signature = signature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TopUp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TopUp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
