# coding: utf-8

"""
    FerryTix

    This is the api for the FerryTix Passenger Ferry Ticketing System, that is both accessible to the vending machines and to other clients.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hendrik.lankers.hl@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VendingMachine(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'public_key': 'str',
        'location': 'MachineLocation'
    }

    attribute_map = {
        'uuid': 'uuid',
        'public_key': 'publicKey',
        'location': 'location'
    }

    def __init__(self, uuid=None, public_key=None, location=None):  # noqa: E501
        """VendingMachine - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._public_key = None
        self._location = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if public_key is not None:
            self.public_key = public_key
        if location is not None:
            self.location = location

    @property
    def uuid(self):
        """Gets the uuid of this VendingMachine.  # noqa: E501


        :return: The uuid of this VendingMachine.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this VendingMachine.


        :param uuid: The uuid of this VendingMachine.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def public_key(self):
        """Gets the public_key of this VendingMachine.  # noqa: E501


        :return: The public_key of this VendingMachine.  # noqa: E501
        :rtype: str
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """Sets the public_key of this VendingMachine.


        :param public_key: The public_key of this VendingMachine.  # noqa: E501
        :type: str
        """

        self._public_key = public_key

    @property
    def location(self):
        """Gets the location of this VendingMachine.  # noqa: E501


        :return: The location of this VendingMachine.  # noqa: E501
        :rtype: MachineLocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this VendingMachine.


        :param location: The location of this VendingMachine.  # noqa: E501
        :type: MachineLocation
        """

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VendingMachine, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VendingMachine):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
